name: Update EzklCoreBindings

on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: macos-latest

    steps:
      - name: Checkout ezkl-ios-rust-porter
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build EzklCoreBindings
        run: cargo run --bin gen-bindings

      - name: Install Git LFS
        run: |
          brew install git-lfs
          git lfs install

      - name: Clone ezkl-ios-port repository
        run: |
          git clone https://github.com/ElusAegis/ezkl-ios-port.git
        env:
          GIT_LFS_SKIP_SMUDGE: "1"

      - name: Fetch LFS objects
        run: |
          cd ezkl-ios-port
          git lfs pull

      - name: Copy EzklCoreBindings
        run: |
          rm -rf ezkl-ios-port/Sources/EzklCoreBindings
          cp -r EzklCoreBindings ezkl-ios-port/Sources/

      - name: Set up Xcode environment
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Run Package Tests
        run: |
          cd ezkl-ios-port
          xcodebuild test \
            -scheme ezkl-ios-port \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest'

      - name: Run Example App Tests
        run: |
          cd ezkl-ios-port/Example
          pod install
          xcodebuild test \
            -workspace EzklApp.xcworkspace \
            -scheme EzklApp \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest'

      - name: Commit and Push Changes
        if: success()
        run: |
          cd ezkl-ios-port
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update EzklCoreBindings from ezkl-ios-rust-porter"
          git push https://$EZKL_PORTER_TOKEN@github.com/ElusAegis/ezkl-ios-port.git main
        env:
          EZKL_PORTER_TOKEN: ${{ secrets.EZKL_PORTER_TOKEN }}