name: Update EzklCoreBindings

on:
  push:
    branches:
      - main
      - feat/ci-updates-for-bindings # TODO: Remove this line after testing

  pull_request:
      branches:
        - main
      types:
        - ready_for_review

  # Option to manually trigger the workflow
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: macos-latest

    steps:
      - name: Checkout ezkl-ios-rust-porter
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build EzklCoreBindings
        run: cargo run --bin gen-bindings

      - name: Install Git LFS
        run: |
          brew install git-lfs
          git lfs install

      - name: Clone ezkl-ios-port repository
        run: |
          git clone https://github.com/ElusAegis/ezkl-ios-port.git
        env:
          GIT_LFS_SKIP_SMUDGE: "1"

      - name: Fetch LFS objects
        run: |
          cd ezkl-ios-port
          git lfs pull

      - name: Copy EzklCoreBindings
        run: |
          rm -rf ezkl-ios-port/Sources/EzklCoreBindings
          cp -r EzklCoreBindings ezkl-ios-port/Sources/

      - name: Set up Xcode environment
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Run Package Tests
        run: |
          cd ezkl-ios-port
          xcodebuild test \
            -scheme EzklPackage \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            -resultBundlePath ../testResults


      # We avoid the UI test because it always times out on GitHub Actions
      - name: Run Example App Tests
        run: |
          cd ezkl-ios-port/Example
          xcodebuild test \
            -project Example.xcodeproj \
            -scheme EzklApp \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            -parallel-testing-enabled NO \
             -resultBundlePath ../../exampleTestResults \
            -skip-testing:EzklAppUITests/EzklAppUITests/testButtonClicksInOrder

      - name: Upload Test Results (Package)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: package-test-results
          path: ./testResults

      - name: Upload Test Results (Example)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: example-app-test-results
          path: ./exampleTestResults

      - name: Commit and Push Changes
        if: success()
        run: |
          cd ezkl-ios-port
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add Sources/EzklCoreBindings
          git commit -m "Update EzklCoreBindings from ezkl-ios-rust-porter"
          git push --set-upstream https://${SWIFT_PACKAGE_OWNER_USERNAME}:${EZKL_PORTER_TOKEN}@github.com/${SWIFT_PACKAGE_OWNER_USERNAME}/ezkl-ios-port.git testing-actions
        env:
          EZKL_PORTER_TOKEN: ${{ secrets.EZKL_PORTER_TOKEN }}
          SWIFT_PACKAGE_OWNER_USERNAME: ${{ vars.SWIFT_PACKAGE_OWNER_USERNAME }}