name: Update EzklCoreBindings

on:
  push:
    branches:
      - main
      - feat/ci-updates-for-bindings # TODO: Remove this line after testing

  pull_request:
      branches:
        - main
      types:
        - ready_for_review

  # Option to manually trigger the workflow
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: macos-latest

    steps:
      - name: Checkout ezkl-ios-rust-porter
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

#      - name: Build EzklCoreBindings
#        run: cargo run --bin gen-bindings

      - name: Install Git LFS
        run: |
          brew install git-lfs
          git lfs install

      - name: Clone ezkl-ios-port repository
        run: |
          git clone https://github.com/ElusAegis/ezkl-ios-port.git
        env:
          GIT_LFS_SKIP_SMUDGE: "1"

      - name: Fetch LFS objects
        run: |
          cd ezkl-ios-port
          git lfs pull

#      - name: Copy EzklCoreBindings
#        run: |
#          rm -rf ezkl-ios-port/Sources/EzklCoreBindings
#          cp -r EzklCoreBindings ezkl-ios-port/Sources/
      - name: Create a random file in ezkl-ios-port/Sources/EzklCoreBindings
        run: |
          echo "This is a random file" > ezkl-ios-port/Sources/EzklCoreBindings/random.txt

      - name: Set up Xcode environment
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

#      - name: Run Package Tests
#        run: |
#          cd ezkl-ios-port
#          xcodebuild test \
#            -scheme EzklPackage \
#            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
#            -resultBundlePath ../testResults
#
#      - name: Run Example App Tests
#        run: |
#          cd ezkl-ios-port/Example
#          xcodebuild test \
#            -project Example.xcodeproj \
#            -scheme EzklApp \
#            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
#            -parallel-testing-enabled NO \
#            -resultBundlePath ../../exampleTestResults
#
#      - name: Upload Test Results (Package)
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: package-test-results
#          path: ./testResults
#
#      - name: Upload Test Results (Example)
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: example-app-test-results
#          path: ./exampleTestResults

      - name: Commit and Push Changes
        if: success()
        run: |
          cd ezkl-ios-port
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Sources/EzklCoreBindings
          git checkout -b testing-actions
          git commit -m "Update EzklCoreBindings from ezkl-ios-rust-porter"
          git config credential.helper 'store --file=.git/credentials'
          echo "https://${SWIFT_PACKAGE_OWNER_USERNAME}:${EZKL_PORTER_TOKEN}@github.com" > .git/credentials
          git push --set-upstream origin testing-actions
        env:
          EZKL_PORTER_TOKEN: ${{ secrets.EZKL_PORTER_TOKEN }}